on:
  push:
    branches: [ master ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.KEY }}
            port: ${{ secrets.PORT }}
            script: |
              cd ~/workplace/nua-bot # navigate into the folder
              git pull
              yarn # install dependencies
              yarn build # build project
              pm2 start ./pm2/ecosystem.config.js # start as a background service.
              
